# Site settings
title: "my world views"
#description: > Just observations, ideas, appreciations etc

author: Asier Berra
email: x
twitter_username: asierberra
github_username: asierberra

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asierberra.github.io" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
